hub:
  db:
    type: sqlite-pvc
    pvc:
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
      storageClassName: standard
  # run only on master nodes
  nodeSelector:
        node-role.kubernetes.io/master: ""
  extraConfig: |
    c.Spawner.http_timeout = 90

proxy:
  # run only on master nodes
  nodeSelector:
        node-role.kubernetes.io/master: ""

singleuser:
  # very small limits for testing on small instances
  memory:
    guarantee: 10G
    limit: 10G
  cpu:
    guarantee: 4
    limit: 10
  storage:
    type: dynamic
    capacity: 5Gi
    dynamic:
      storageClass: standard
  image:
    name: supercdms/cdms-jupyterlab
    tag: 1.8b
  cmd: /opt/rh/rh-python36/root/usr/bin/jupyter-labhub
  startTimeout: 900
  defaultUrl: "/lab"
  # default is 300s, sometimes Jetstream volumes are slow to attach
  startTimeout: 600
