hub:
  db:
    type: sqlite-pvc
    pvc:
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
      storageClassName: standard
  # run only on master nodes
  nodeSelector:
        node-role.kubernetes.io/master: ""
  extraConfig: |
    c.Spawner.http_timeout = 90

proxy:
  # run only on master nodes
  nodeSelector:
        node-role.kubernetes.io/master: ""

singleuser:
  extraTolerations:
    - key: "CriticalAddonsOnly"
      operator: "Equal"
      value: "True"
      effect: "NoSchedule"
    - key: "dedicated"
      operator: "Equal"
      value: "master"
      effect: "NoSchedule"
  # very small limits for testing on small instances
  memory:
    guarantee: 3G
    limit: 3G
  cpu:
    guarantee: 1
    limit: 1
  storage:
    type: dynamic
    capacity: 10Gi
    dynamic:
      storageClass: standard
    extraVolumes:
        - name: cvmfs-nfs-volume
          nfs:
            server: 10.254.77.77
            path: /
    extraVolumeMounts:
        - name: cvmfs-nfs-volume
          mountPath: /cvmfs
          readOnly: true
  image:
    name: "zonca/docker-jupyter-cdms-light"
    tag: "latest"
  defaultUrl: "/lab"
  # default is 300s, sometimes Jetstream volumes are slow to attach
  startTimeout: 600
