hub:
  db:
    type: sqlite-pvc
    pvc:
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
      storageClassName: standard
  # run only on master nodes
  nodeSelector:
        node-role.kubernetes.io/master: ""
  extraConfig: |
    c.Spawner.http_timeout = 90
    c.Spawner.args = [
          "--ResourceUseDisplay.track_cpu_percent=True",
    ]
  tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: Exists

proxy:
  # run only on master nodes
  chp:
      nodeSelector:
            node-role.kubernetes.io/master: ""
      tolerations:
          - key: "node-role.kubernetes.io/master"
            operator: Exists

singleuser:
  memory:
      guarantee: 5G
      limit: 5G
  cpu:
      guarantee: 2
      limit: 6
  profileList:
    - display_name: "Default: 2-6 CPUs and 5 GB RAM"
      default: True
    - display_name: "Tiny: 1-3 CPUs and 3 GB RAM"
      kubespawner_override:
        cpu_limit: 3
        cpu_guarantee: 1
        mem_limit: 3G
        mem_guarantee: 3G
    - display_name: "Full node: 20-24 CPUs and 50 GB RAM"
      kubespawner_override:
        cpu_limit: 24
        cpu_guarantee: 20
        mem_limit: 50G
        mem_guarantee: 50G
  storage:
    type: dynamic
    capacity: 10Gi
    dynamic:
      storageClass: standard
    extraVolumes:
        - name: cvmfs-nfs-volume
          nfs:
            # for Magnum
            # server: 10.254.77.77
            # for Kubespray
            server: 10.233.46.63
            path: /
    extraVolumeMounts:
        - name: cvmfs-nfs-volume
          mountPath: /cvmfs
          readOnly: false
  image:
    name: "zonca/docker-jupyter-cdms-light"
    tag: "2021.03.17"
  defaultUrl: "/lab"
  # default is 300s, sometimes Jetstream volumes are slow to attach
  startTimeout: 600
  lifecycleHooks:
    postStart:
      exec:
        command:
           - "sh"
           - "-c"
           - >
             chmod 700 .ssh;
             chmod g-s .ssh;
             chmod 600 .ssh/*;
             exit 0
