hub:
  db:
    type: sqlite-pvc
    pvc:
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
      storageClassName: standard
  # run only on master nodes
  nodeSelector:
        node-role.kubernetes.io/master: ""
  extraConfig: |
    c.Spawner.http_timeout = 90
    c.Spawner.args = [
          "--ResourceUseDisplay.track_cpu_percent=True",
    ]

proxy:
  # run only on master nodes
  nodeSelector:
        node-role.kubernetes.io/master: ""

singleuser:
  # very small limits for testing on small instances
  memory:
    guarantee: 3G
    limit: 3G
  cpu:
    guarantee: 1
    limit: 1
  storage:
    type: dynamic
    capacity: 10Gi
    dynamic:
      storageClass: standard
    extraVolumes:
        - name: cvmfs-nfs-volume
          nfs:
            # for Magnum
            # server: 10.254.77.77
            # for Kubespray
            server: 10.233.46.63
            path: /
    extraVolumeMounts:
        - name: cvmfs-nfs-volume
          mountPath: /cvmfs
          readOnly: false
  image:
    name: "zonca/docker-jupyter-cdms-light"
    tag: "2020.07"
  defaultUrl: "/lab"
  # default is 300s, sometimes Jetstream volumes are slow to attach
  startTimeout: 600
