apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-8712010b-7512-11ea-a548-fa163eeabf17
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Gi
  cinder:
    volumeID: 7681ccc9-7bdb-470f-bd6d-43587e2c2328
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-pv-claim
    namespace: default
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
